sudo: required
language: node_js
node_js:
    - "12"
services:
    - docker

before_install:
    - docker build -t samirprakash/docker-react:develop -f Dockerfile.dev .

script:
    - docker run samirprakash/docker-react:develop npm run test -- --coverage --watchAll=false
