sudo: required
services:
    - docker

before_install:
    - docker build -t samirprakash/docker-react -f Dockerfile.dev .

script:
    - docker run samirprakash/docker-react npm run test -- --coverage
