version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: samirprakash/docker-react:develop
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
      build:
        context: .
        dockerfile: Dockerfile.dev
      image: samirprakash/docker-react:develop
      volumes:
        - /app/node_modules
        - .:/app
      command: ["npm", "run", "test"]
      